@echo off
REM Real-life style pipeline run: Kafka as transport, Lakehouse (MinIO + Delta) as persistence
REM Prerequisites: docker-compose up -d broker zookeeper control-center minio

echo ==========================================
echo Lambda Architecture - Real-Life Flow ^(Kafka -^> Lakehouse^)
echo ==========================================
echo.

REM Change to project root directory (where this script is located)
cd /d "%~dp0\.."
echo Working directory: %CD%
echo.

REM Step 0: Cleanup local CSV outputs (Lakehouse will be used)
echo [0/5] Cleaning up local CSV outputs...
if exist "data\batch_views\*.csv" del /q "data\batch_views\*.csv"
if exist "data\speed_views\*.csv" del /q "data\speed_views\*.csv"
if exist "data\serving_views\*.csv" del /q "data\serving_views\*.csv"
if exist "data\serving_views\plots\*.png" del /q "data\serving_views\plots\*.png"
if exist "data\raw\traffic_raw.json" del /q "data\raw\traffic_raw.json"
echo Cleanup complete.
echo.

REM Step 1: Periodic ingestion note
echo [1/5] Periodic ingestion (Traffic + Air) -> Kafka
echo In production, traffic and air API data would be ingested periodically into Kafka.
echo We simulate this with a single run that writes data to Kafka.
set /p "=Press ENTER to start ingestion into Kafka... "
echo.

REM Ingestion into Kafka (Raw Topics)
REM Air Quality data is already available in the data/raw/air_raw.json file
REM Traffic data is generated by the generate_traffic_data.py script for simulation
REM IF you need real data, you can use the python main.py dataset --use-api both --use-kafka command
echo Pushing traffic data to Kafka...
uv run python generate_traffic_data.py >nul 2>&1
uv run python main.py dataset --use-api traffic --use-kafka --from-file >nul 2>&1
echo Pushing air quality data to Kafka...
uv run python main.py dataset --use-api air --use-kafka --from-file >nul 2>&1
if errorlevel 1 (
    echo Error during ingestion into Kafka.
    exit /b 1
)
echo Raw data written to Kafka: traffic-raw, air-quality-raw
echo.

REM Step 2: Batch Layer reads from Kafka, writes views to Lakehouse
echo [2/5] Batch Layer: reads from Kafka, writes traffic/batch_view to Lakehouse
echo Resetting consumer group offset to read messages from beginning...
docker exec broker kafka-consumer-groups --bootstrap-server localhost:9092 --group lambda-batch-consumer --reset-offsets --to-earliest --topic traffic-raw --execute >nul 2>&1
echo Re-pushing traffic data to Kafka for Batch Layer processing...
uv run python main.py dataset --use-api traffic --use-kafka --from-file >nul 2>&1
set /p "=Press ENTER to start the Batch Layer... "
echo.

uv run python main.py batch --use-kafka --use-lakehouse >nul 2>&1
if errorlevel 1 (
    echo Error in Batch Layer.
    exit /b 1
)
echo Batch view (traffic/batch_view) updated in Lakehouse.
echo.

REM Step 3: Speed Layer reads from Kafka, writes views to Lakehouse
echo [3/5] Speed Layer: reads from Kafka, writes air_quality/speed_view to Lakehouse
echo Resetting consumer group offset to read messages from beginning...
docker exec broker kafka-consumer-groups --bootstrap-server localhost:9092 --group lambda-speed-consumer --reset-offsets --to-earliest --topic air-quality-raw --execute >nul 2>&1
echo Re-pushing air quality data to Kafka for Speed Layer processing...
uv run python main.py dataset --use-api air --use-kafka --from-file >nul 2>&1
set /p "=Press ENTER to start the Speed Layer... "
echo.

uv run python main.py speed --use-kafka --use-lakehouse >nul 2>&1
if errorlevel 1 (
    echo Error in Speed Layer.
    exit /b 1
)
echo Speed view (air_quality/speed_view) updated in Lakehouse.
echo.

REM Step 4: Serving Layer reads from Lakehouse, writes Combined View to Lakehouse
echo [4/5] Serving Layer: reads Batch+Speed views from Lakehouse, writes serving/combined_view
set /p "=Press ENTER to start the Serving Layer... "
echo.

uv run python main.py serving --use-lakehouse >nul 2>&1
if errorlevel 1 (
    echo Error in Serving Layer.
    exit /b 1
)
echo Combined view (serving/combined_view) updated in Lakehouse.
echo.

REM Done
echo ==========================================
echo Pipeline ^(Kafka -^> Lakehouse^) completed.
echo Lakehouse tables:
echo   - traffic/raw
echo   - air_quality/raw
echo   - traffic/batch_view
echo   - air_quality/speed_view
echo   - serving/combined_view
echo ==========================================
echo.

